version: '3.8'
services:
  # Backend API service
  backend:
    image: ${REGISTRY_URL}/figure-collector-backend:${BACKEND_TAG:-latest}
    restart: always
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGODB_URI=${MONGODB_URI}
      - JWT_SECRET=${JWT_SECRET}
    ports:
      - "5000:5000"
    networks:
      - figure-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    labels:
      coolify.enable: "true"
      coolify.name: "figure-collector-backend"
      coolify.type: "application"
      coolify.autodeploy: "true"

  # Frontend application
  frontend:
    image: ${REGISTRY_URL}/figure-collector-frontend:${FRONTEND_TAG:-latest}
    restart: always
    environment:
      - REACT_APP_API_URL=/api
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - figure-network
    labels:
      coolify.enable: "true"
      coolify.name: "figure-collector-frontend"
      coolify.type: "application"
      coolify.autodeploy: "true"

networks:
  figure-network:
    driver: bridge
